sonar.projectKey=Ghalia789_studyspark
sonar.organization=ghalia789
sonar.projectName=StudySpark
sonar.sources=src
sonar.exclusions=node_modules/**,.next/**,public/**,src/**/__tests__/**,src/**/*.test.ts,src/**/*.test.tsx
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info